Math3 2021 + 1370 ALL
Gp2mv3/Syntheses pull request #879
Opened 2021-06-22 15:09 UTC by Bbalon-a

Update des examens de circuit et mesures 1370 + examen Math 3 2021

2022-01-01 12:26 UTC, blegat commented on src/q4/circmes-ELEC1370/exam/2018/Juin/Majeure/circmes-ELEC1370-exam-2018-Juin-Majeure.tex
> +\usepackage{SIunits}
Ça ne compile pas à cause de https://tex.stackexchange.com/questions/138807/usepackagesiunits-error-square-already-defined.
Sais-tu changer pour utiliser `siunitx` ?

2022-01-01 12:27 UTC, blegat commented
Merci pour ta contribution, note l'appel au maintainers https://github.com/Gp2mv3/Syntheses/pull/884/ ;)

2023-01-02 15:02 UTC, ldevillez requested changes

2023-01-02 15:02 UTC, ldevillez commented on src/q3/edp-EPL1103/exam/2021/Janvier/All/edp-EPL1103-exam-2021-Janvier-All.tex
> +    y^{2n-1} \frac{du}{dx} - x^{2n-1} \frac{du}{dy} = \frac{y^{4n-1}}{x^{2n-1}} U
Il faut réparer ici (cf #894 )

2023-01-02 15:02 UTC, ldevillez commented on src/q3/edp-EPL1103/exam/2021/Janvier/All/edp-EPL1103-exam-2021-Janvier-All.tex
> +et ce à l'intérieur d'un secteur de disque de rayon et d'angle d'ouverture $\beta = \frac{2\pi}{3}$. On impose que $u(a,\theta) = U(\frac{\theta}{\beta})^2$ avec U constant, tel que $\frac{\partial u
Et ici (#894 )

2023-11-28 11:06 UTC, closed without merging